- include_tasks: nginx.yml

- name: Inject the NGINX loadbalancer configuration
  template:
    dest: '/etc/nginx/nginx.conf'
    src: nginx.conf.j2
    mode: 0700
    owner: root
    group: root
  notify: Restart nginx
